version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: timebank_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: timebank
      MYSQL_USER: timebank_user
      MYSQL_PASSWORD: tb_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: timebank_backend
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev --name init && npm run dev"
    environment:
      DATABASE_URL: mysql://timebank_user:tb_password@db:3306/timebank
      JWT_SECRET: your_jwt_secret
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: timebank_frontend
    environment:
      VITE_API_URL: http://localhost:4000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db_data:
